/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tangyx_video_ffmpeg_FFmpegRun */

#ifndef _Included_com_jarhero790_eub_record_ffem_FFmpegRun
#define _Included_com_jarhero790_eub_record_ffem_FFmpegRun
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tangyx_video_ffmpeg_FFmpegRun
 * Method:    run
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jarhero790_eub_record_ffem_FFmpegRun_run
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
